# Generated by Django 2.2.5 on 2020-06-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'My_resume'},
        ),
    ]
