# Generated by Django 2.2.5 on 2020-06-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20200611_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='createproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
